/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 157bf9681e7cd013dac768b0664566a2)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "ChatSessionDurableObject" | "BrowserSessionDurableObject";
	}
	interface Env {
		ASSETS: Fetcher;
		OPENROUTER_API_KEY: string;
		OPENROUTER_MODEL: string;
		OPENROUTER_SITE_URL: string;
		OPENROUTER_SITE_NAME: string;
		BROWSER_SESSIONS: DurableObjectNamespace<import("./src/worker").BrowserSessionDurableObject>;
		CHAT_SESSIONS: DurableObjectNamespace<import("./src/worker").ChatSessionDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENROUTER_API_KEY" | "OPENROUTER_MODEL" | "OPENROUTER_SITE_URL" | "OPENROUTER_SITE_NAME">> {}
}
